# .github/workflows/score_daily.yml
name: Daily AI Score (Polygon)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "25 12 * * 1-5"  # 12:25 UTC on weekdays; adjust to your premarket window

permissions:
  contents: write

jobs:
  score:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy joblib scikit-learn

      # If your screener produces a CSV here, ensure it's present before scoring.
      # Otherwise, daily_ai_score.py will explain what's missing.
      - name: Run daily scorer
        run: |
          python scripts/daily_ai_score.py

      - name: Commit today_scores.json
        run: |
          if [ -f public/today_scores.json ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add public/today_scores.json
            git commit -m "Update today_scores.json [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "public/today_scores.json was not produced."
            exit 1
          fi
