name: Daily AI Score (Polygon)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "25 12 * * 1-5"  # adjust to your premarket window

permissions:
  contents: write

jobs:
  score:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
      # OPTIONAL: provide tickers here or via repo/organization env/secret
      # CANDIDATE_TICKERS: "AAPL,TSLA,AMD"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy joblib scikit-learn requests python-dateutil

      - name: Try to build candidates from Polygon (if none found)
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          CANDIDATE_TICKERS: ${{ vars.CANDIDATE_TICKERS }}
        run: |
          # If we already have a candidate CSV, skip build.
          if [ -f latest_screener.csv ] || [ -f public/latest_screener.csv ] || [ -f data/latest_screener.csv ] || [ -f public/today_candidates.csv ]; then
            echo "Candidate CSV already present. Skipping build."
          else
            echo "No candidate CSV found. Attempting to build from Polygon…"
            python scripts/build_candidates_from_polygon.py
          fi

      - name: Run daily scorer
        run: |
          python scripts/daily_ai_score.py

      - name: Commit today_scores.json
        run: |
          if [ -f public/today_scores.json ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add public/today_scores.json latest_screener.csv || true
            git commit -m "Update today_scores.json [skip ci]" || echo "No changes to commit"
            git push || true
          else
            echo "public/today_scores.json was not produced."
            exit 1
          fi
