name: Daily AI Score (Polygon)

on:
  workflow_dispatch: {}
  # premarket on weekdays (adjust if you like)
  schedule:
    - cron: "30 12 * * 1-5"   # 12:30 UTC ≈ 08:30 ET

permissions:
  contents: write

jobs:
  score:
    runs-on: ubuntu-latest
    env:
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy requests python-dateutil tenacity scikit-learn joblib

      # Use whichever script you created. If you have both, prefer score_today.py.
      - name: Build today_scores.json
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          set -euo pipefail
          if [ -f scripts/score_today.py ]; then
            python scripts/score_today.py --out public/today_scores.json
          else
            python scripts/create_score_today_from_csv.py --out public/today_scores.json
          fi
          echo "== ls public =="
          ls -lh public || true
          echo "== preview =="
          head -c 400 public/today_scores.json || true
          echo

      - name: Commit JSON (trigger Vercel deploy)
        run: |
          set -euo pipefail
          git config user.email "bot@github"
          git config user.name  "actions-bot"
          git add -A public/today_scores.json
          git commit -m "chore: update today_scores.json" || echo "Nothing to commit"
          git pull --rebase origin main || true
          git push || true

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: today_scores
          path: public/today_scores.json
          if-no-files-found: error
