name: Daily AI Score (Polygon)

on:
  workflow_dispatch:
  schedule:
    # 9:35am US/Eastern, Mon–Fri
    - cron: '35 13 * * 1-5'

jobs:
  score:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy scikit-learn requests tenacity python-dateutil pyarrow joblib

      - name: Build today's scores
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          set -euo pipefail
          mkdir -p public

          # If your script writes to public directly, use this:
          # python scripts/create_score_today_from_csv.py --model ai_score.joblib --out public/today_scores.json

          # If your existing script writes to data/today_scores.json, keep this block:
          python scripts/create_score_today_from_csv.py
          if [ -f data/today_scores.json ]; then
            mv -f data/today_scores.json public/today_scores.json
          fi

          echo "Preview:"
          head -c 600 public/today_scores.json || true
          echo; echo "Public dir:"; ls -al public

      - name: Commit today_scores.json
        run: |
          git config user.email "bot@github"
          git config user.name  "actions-bot"
          git add public/today_scores.json
          git commit -m "Update today_scores.json" || echo "Nothing to commit"
          git push || true

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: today_scores
          path: public/today_scores.json
          if-no-files-found: warn
