# .github/workflows/score_daily.yml
name: Daily AI Score (Finviz → News → optional Polygon → JSON)

on:
  workflow_dispatch:
  schedule:
    - cron: "20 12 * * 1-5"  # ~08:20 ET on weekdays; adjust as needed

jobs:
  score:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FINVIZ_EXPORT_URL: ${{ secrets.FINVIZ_EXPORT_URL }}
      FINVIZ_NEWS_EXPORT_URL: ${{ secrets.FINVIZ_NEWS_EXPORT_URL }}
      FINVIZ_FILINGS_EXPORT_URL: ${{ secrets.FINVIZ_FILINGS_EXPORT_URL }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      MODEL_PATH: "ai_score.joblib"
      OUT_JSON: "public/today_scores.json"
      PRICE_MIN: "1"
      PRICE_MAX: "5"
      DAILY_FALLBACK: "1"

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas requests joblib scikit-learn

      - name: Fetch Finviz candidates
        run: python scripts/fetch_finviz_candidates.py

      - name: Fetch Finviz news
        run: python scripts/fetch_finviz_news.py

      - name: Score (ML if Polygon ok; Finviz fallback otherwise)
        run: python scripts/daily_ai_score.py

      - name: Commit & push JSON/CSVs
        run: |
          git config user.email "bot@github"
          git config user.name  "actions-bot"
          git add public/today_candidates.csv public/today_tickers.txt public/today_scores.json public/today_news.json
          git commit -m "Premarket: candidates, news, today_scores" || echo "No changes"
          git push || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: premarket_payload
          path: |
            public/today_candidates.csv
            public/today_scores.json
            public/today_news.json
