# .github/workflows/score_daily.yml
name: Daily AI Score (Polygon)

on:
  workflow_dispatch: {}
  schedule:
    # Mon–Fri 13:35 UTC ~ 09:35 ET (adjust as you like)
    - cron: "35 13 * * 1-5"

jobs:
  score:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

      # Finviz is the authority for which tickers to score
      UNIVERSE_SOURCE: FINVIZ_FILE
      FINVIZ_FILE_PATH: public/finviz_universe.json
      STRICT_FINVIZ: "true"

      # Price band (ignored when STRICT_FINVIZ=true)
      PRICE_MIN: "1"
      PRICE_MAX: "5"

      MAX_TICKERS: "100"
      MODEL_PATH: models/ai_score.joblib
      OUT_PATH: public/today_scores.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U requests numpy tenacity joblib

      - name: Build today_scores.json
        run: |
          python scripts/score_today_from_polygon.py

      - name: Commit JSON (trigger Vercel deploy)
        run: |
          git config user.email "bot@github"
          git config user.name  "actions-bot"
          git add public/today_scores.json
          git commit -m "Update today_scores.json" || true
          git push || true

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: today_scores
          path: public/today_scores.json
