name: Snapshot Cron

on:
  schedule:
    - cron: "*/5 * * * 1-5"   # every 5 minutes on weekdays (UTC)
  workflow_dispatch: {}       # allow manual run from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron-snapshot
        run: |
          set -e
          RESP=$(curl -sS -H "Authorization: Bearer ${CRON_SECRET}" "${SNAPSHOT_URL}")
          echo "$RESP"
          # Fail the job if API didn't return ok:true
          echo "$RESP" | grep -q '"ok":true'
    env:
      SNAPSHOT_URL: ${{ secrets.SNAPSHOT_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
