name: Train AI Score — Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy scikit-learn joblib

      - name: Stitch monthly CSVs → training_all.csv
        shell: bash
        run: |
          shopt -s nullglob
          files=(training/training_*.csv)
          echo "Found ${#files[@]} month files."
          if [ ${#files[@]} -eq 0 ]; then
            echo "No training/*.csv yet. Nothing to train."; exit 0
          fi
          python - <<'PY'
          import glob, pandas as pd
          files = sorted(glob.glob('training/training_*.csv'))
          df = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)
          print("stitched shape:", df.shape)
          df.to_csv('training_all.csv', index=False)
          PY

      - name: Train model
        run: |
          mkdir -p models
          python scripts/train_ai_score.py
          [ -f ai_score.joblib ] && mv -f ai_score.joblib models/ai_score.joblib
          [ -f metrics.json ] && mv -f metrics.json models/metrics.json
          test -f models/ai_score.joblib

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-training-data
          path: |
            training_all.csv
            models/**

      - name: Commit model to repo
        run: |
          git config user.email "bot@github"
          git config user.name "actions-bot"
          git add training_all.csv models/ || true
          git commit -m "Train model $(date -u +%F)" || echo "Nothing to commit"
          git push || true
