# .github/workflows/train_model.yml
name: Train AI Score — Model

on:
  workflow_dispatch: {}

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U pandas numpy scikit-learn joblib

      - name: Stitch monthly CSVs → training_all.csv
        run: |
          set -euo pipefail
          if ls training/training_*.csv 1>/dev/null 2>&1; then
            head -n1 training/training_*.csv | head -n1 > training_all.csv
            for f in training/training_*.csv; do
              tail -n +2 "$f" >> training_all.csv
            done
            echo "Built training_all.csv"
          else
            if [ -f training_all.csv ]; then
              echo "Using existing training_all.csv"
            else
              echo "No training CSVs found."; exit 1
            fi
          fi

      - name: Train model
        run: |
          python scripts/train_ai_score.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: |
            models/ai_score.joblib
            metrics.json
          if-no-files-found: error

      - name: Commit model to repo
        run: |
          git config user.email "bot@github"
          git config user.name  "actions-bot"
          git add models/ai_score.joblib metrics.json
          git commit -m "Update ai_score model and metrics" || true
          git push || true
